preprocess:
  input_one: data/raw/Fake.csv
  input_two: data/raw/True.csv
  output: data/processed/data.csv

train:
  data: data/processed/data.csv
  model: models/model.pkl
  random_state: 42
  n_estimators: 100
  max_depth: 5